[workspace]
members = [
    "can-attachment", "clock-face",
    "stick-up-cam-mk4",
]
resolver = "2"

[workspace.dependencies]
#rsolid = { git = "https://github.com/camshaft/rsolid" }
rsolid = { path = "../rsolid/rsolid" }
